jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/Girbons/comics-downloader

    environment:
      GOOS: linux
      GOARCH: amd64
      GOPATH: /go

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -t -d -v ./...
      - run:
          name: Build all
          command: go build ./...
      - run:
          name: Test all
          command: go test -v ./...
