jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/Girbons/comics-downloader

    environment:
      GOOS: linux
      GOARCH: amd64
      GOPATH: /go

    steps:
      - checkout
      - run:
          name: Get dependencies
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
            go get github.com/mattn/goveralls
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Run tests
          command: go test -v ./...

      - run:
          name: Run golangci-lint
          command: golangci-lint run
